# Generated by Django 5.0.7 on 2024-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('opening_hours', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchens/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
