# Generated by Django 5.0.7 on 2024-08-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodano', '0002_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='opening_hours',
        ),
    ]
